#pragma once

#include <stdint.h>

// Generated by tools/generate_board_header.py from picocalc-rp2040.json.
// Do not edit this file directly; edit the JSON profile and regenerate it.

namespace picocalc::board {

constexpr uint32_t kSystemClockKhz = 250000;
constexpr uint32_t kUartBaudRate = 115200;
constexpr unsigned kLcdSck = 10;
constexpr unsigned kLcdMosi = 11;
constexpr unsigned kLcdMiso = 12;
constexpr unsigned kLcdCs = 13;
constexpr unsigned kLcdDc = 14;
constexpr unsigned kLcdReset = 15;
constexpr unsigned kLcdRamCs = 21;
constexpr uint8_t kLcdMadctl = 0x48;
constexpr uint8_t kLcdColmod = 0x66;
constexpr unsigned kSdMiso = 16;
constexpr unsigned kSdCs = 17;
constexpr unsigned kSdSck = 18;
constexpr unsigned kSdMosi = 19;
constexpr unsigned kSdDetect = 22;
constexpr uint32_t kSdInitHz = 400000;
constexpr uint32_t kSdRunHz = 12000000;
constexpr unsigned kPsramCs = 20;
constexpr unsigned kPsramSck = 21;
constexpr unsigned kPsramMosi = 2;
constexpr unsigned kPsramMiso = 3;
constexpr unsigned kKeyboardSda = 6;
constexpr unsigned kKeyboardScl = 7;
constexpr uint32_t kKeyboardHz = 400000;
constexpr uint8_t kKeyboardAddress = 0x1f;
constexpr uint8_t kKeyboardStatusRegister = 0x04;
constexpr uint8_t kKeyboardFifoRegister = 0x09;
constexpr unsigned kAudioLeft = 26;
constexpr unsigned kAudioRight = 27;
constexpr uint32_t kAudioReferenceSampleRateHz = 48000;
constexpr uint8_t kAudioReferencePwmWrap = 0xff;
constexpr int kDisplayWidth = 320;
constexpr int kDisplayHeight = 320;
constexpr int kDisplayGramWidth = 320;
constexpr int kDisplayGramHeight = 480;
constexpr int kLcdMaxPixelsPerCs = 160;
constexpr float kLcdPioClockDivider = 4.0f;

}  // namespace picocalc::board
