#!/usr/bin/env python3
"""Generate the repository-owned deterministic VRP-NES-0 NROM fixture.

The fixture is intentionally small and synthetic.  It is not copied from a
cartridge or from a third-party ROM: the iNES header, 6502 reset program,
trainer bytes, and CHR pattern are generated by this file.
"""

from __future__ import annotations

import argparse
import hashlib
from pathlib import Path


HEADER_SIZE = 16
TRAINER_SIZE = 512
PRG_SIZE = 0x8000  # NROM-256: two 16 KiB banks
CHR_SIZE = 0x2000  # one 8 KiB CHR-ROM bank


def build_image() -> bytes:
    """Return the exact 41,488-byte NROM-256 image."""

    # Trainer bytes are deterministic and deliberately non-zero so the
    # oracle can prove that the complete iNES image, not only PRG/CHR, was
    # loaded.  The trainer flag also places this image at the M-NESCO flash
    # threshold, exercising the XIP-backed SD path.
    header = bytearray(b"NES\x1a")
    header.extend((2, 1, 0x04, 0x00))  # PRG=32 KiB, CHR=8 KiB, mapper 0 + trainer
    header.extend(b"\x00" * 8)

    trainer = bytes((0xA5 ^ (index * 29)) & 0xFF for index in range(TRAINER_SIZE))
    prg = bytearray(b"\xEA" * PRG_SIZE)  # deterministic NOP fill

    # Reset entry at $8000.  It disables interrupts, clears the display and
    # audio enables, writes a palette and a short nametable prefix, enables
    # background rendering, and then remains in a deterministic tight loop.
    # PPU rendering therefore exercises both CPU ROM fetches and CHR reads.
    program = bytes(
        (
            0x78,  # SEI
            0xD8,  # CLD
            0xA2, 0xFF,  # LDX #$FF
            0x9A,  # TXS
            0xA9, 0x00,  # LDA #$00
            0x8D, 0x00, 0x20,  # STA $2000 (NMI/rendering off while configuring)
            0x8D, 0x01, 0x20,  # STA $2001
            0x8D, 0x10, 0x40,  # STA $4010 (DMC off)
            0x8D, 0x15, 0x40,  # STA $4015 (APU channels off)
            0xA9, 0x3F,  # LDA #$3F
            0x8D, 0x06, 0x20,  # STA $2006
            0xA9, 0x00,  # LDA #$00
            0x8D, 0x06, 0x20,  # STA $2006
            0xA9, 0x0F,  # LDA #$0F
            0x8D, 0x07, 0x20,  # STA $2007 (palette entry)
            0xA9, 0x20,  # LDA #$20
            0x8D, 0x06, 0x20,  # STA $2006
            0xA9, 0x00,  # LDA #$00
            0x8D, 0x06, 0x20,  # STA $2006
            0xA2, 0x20,  # LDX #$20
            0xA9, 0x01,  # LDA #$01
            # fill: STA $2007; DEX; BNE fill
            0x8D, 0x07, 0x20,
            0xCA,
            0xD0, 0xFA,
            0xA9, 0x00,  # LDA #$00
            0x8D, 0x00, 0x20,  # STA $2000 (background table 0)
            0xA9, 0x1E,  # LDA #$1E (background + sprites on)
            0x8D, 0x01, 0x20,  # STA $2001
            0x4C, 0x36, 0x80,  # JMP $8036 (tight loop below)
            0xEA,  # padding at $8036 is replaced by the loop target below
        )
    )
    # The final JMP above targets the first byte after this marker.  Keep the
    # target explicit rather than relying on assembler or linker behavior.
    loop_offset = len(program)
    program += bytes((0x4C, loop_offset & 0xFF, 0x80))
    # Correct the target operand in the preceding JMP to the actual offset.
    jmp_index = program.index(bytes((0x4C, 0x36, 0x80)))
    program = bytearray(program)
    program[jmp_index + 1] = loop_offset & 0xFF
    program[jmp_index + 2] = 0x80
    prg[: len(program)] = program

    # NMI, RESET, IRQ/BRK vectors all point to reset.  No interrupts are
    # enabled, but valid vectors make the image valid for general readers.
    vector_offset = PRG_SIZE - 6
    for offset in (vector_offset, vector_offset + 2, vector_offset + 4):
        prg[offset : offset + 2] = b"\x00\x80"

    # Every CHR byte is deterministic and non-zero in a repeating pattern.
    # This guarantees visible pattern-table bus activity once rendering is on.
    chr_rom = bytes((index * 37 + (index >> 5) + 0x11) & 0xFF for index in range(CHR_SIZE))
    image = bytes(header) + trainer + bytes(prg) + chr_rom
    assert len(image) == HEADER_SIZE + TRAINER_SIZE + PRG_SIZE + CHR_SIZE
    return image


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("output", type=Path, help="output .nes path")
    args = parser.parse_args()
    image = build_image()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_bytes(image)
    print(f"bytes={len(image)} sha256={hashlib.sha256(image).hexdigest()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
