#!/usr/bin/env python3
"""Generate the canonical C++ board constants from the JSON profile."""

import argparse
import json
import sys
from pathlib import Path
from typing import Any, Dict, List, Tuple


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_PROFILE = ROOT / "profiles/picocalc-rp2040.json"
DEFAULT_OUTPUT = ROOT / "bsp/include/picocalc/board_generated.h"

Mapping = Tuple[str, str, str]

MAPPINGS: List[Mapping] = [
    ("system_clock_khz", "uint32_t", "kSystemClockKhz"),
    ("uart_baud_rate", "uint32_t", "kUartBaudRate"),
    ("display.pins.sck", "unsigned", "kLcdSck"),
    ("display.pins.mosi", "unsigned", "kLcdMosi"),
    ("display.pins.miso", "unsigned", "kLcdMiso"),
    ("display.pins.cs", "unsigned", "kLcdCs"),
    ("display.pins.dc", "unsigned", "kLcdDc"),
    ("display.pins.reset", "unsigned", "kLcdReset"),
    ("display.pins.ram_cs", "unsigned", "kLcdRamCs"),
    ("display.madctl", "uint8_t", "kLcdMadctl"),
    ("display.colmod", "uint8_t", "kLcdColmod"),
    ("sd.miso", "unsigned", "kSdMiso"),
    ("sd.cs", "unsigned", "kSdCs"),
    ("sd.sck", "unsigned", "kSdSck"),
    ("sd.mosi", "unsigned", "kSdMosi"),
    ("sd.detect", "unsigned", "kSdDetect"),
    ("sd.init_hz", "uint32_t", "kSdInitHz"),
    ("sd.run_hz", "uint32_t", "kSdRunHz"),
    ("psram.cs", "unsigned", "kPsramCs"),
    ("psram.sck", "unsigned", "kPsramSck"),
    ("psram.mosi", "unsigned", "kPsramMosi"),
    ("psram.miso", "unsigned", "kPsramMiso"),
    ("keyboard.sda", "unsigned", "kKeyboardSda"),
    ("keyboard.scl", "unsigned", "kKeyboardScl"),
    ("keyboard.frequency_hz", "uint32_t", "kKeyboardHz"),
    ("keyboard.address", "uint8_t", "kKeyboardAddress"),
    ("keyboard.status_register", "uint8_t", "kKeyboardStatusRegister"),
    ("keyboard.fifo_register", "uint8_t", "kKeyboardFifoRegister"),
    ("audio.left", "unsigned", "kAudioLeft"),
    ("audio.right", "unsigned", "kAudioRight"),
    (
        "audio.reference_sample_rate_hz",
        "uint32_t",
        "kAudioReferenceSampleRateHz",
    ),
    ("audio.reference_pwm_wrap", "uint8_t", "kAudioReferencePwmWrap"),
    ("display.visible_width", "int", "kDisplayWidth"),
    ("display.visible_height", "int", "kDisplayHeight"),
    ("display.gram_width", "int", "kDisplayGramWidth"),
    ("display.gram_height", "int", "kDisplayGramHeight"),
    ("display.max_pixels_per_cs", "int", "kLcdMaxPixelsPerCs"),
    ("display.pio_clock_divider", "float", "kLcdPioClockDivider"),
]


def nested(data: Dict[str, Any], path: str) -> Any:
    value: Any = data
    for key in path.split("."):
        value = value[key]
    return value


def cpp_value(value: Any, cpp_type: str) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if cpp_type == "float":
        return "{:.1f}f".format(float(value))
    if cpp_type == "uint8_t":
        return "0x{:02x}".format(int(value))
    return str(value)


def render(profile: Dict[str, Any], profile_path: Path) -> str:
    lines = [
        "#pragma once",
        "",
        "#include <stdint.h>",
        "",
        "// Generated by tools/generate_board_header.py from {}.".format(
            profile_path.name
        ),
        "// Do not edit this file directly; edit the JSON profile and regenerate it.",
        "",
        "namespace picocalc::board {",
        "",
    ]
    for profile_key, cpp_type, constant_name in MAPPINGS:
        lines.append(
            "constexpr {} {} = {};".format(
                cpp_type,
                constant_name,
                cpp_value(nested(profile, profile_key), cpp_type),
            )
        )
    lines.extend(["", "}  // namespace picocalc::board", ""])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--profile", type=Path, default=DEFAULT_PROFILE)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail instead of writing when the generated output differs",
    )
    args = parser.parse_args()

    try:
        with args.profile.open("r", encoding="utf-8") as source:
            profile = json.load(source)
        generated = render(profile, args.profile)
    except (OSError, ValueError, TypeError, KeyError) as error:
        print("error: cannot generate board header: {}".format(error), file=sys.stderr)
        return 2

    if args.check:
        try:
            current = args.output.read_text(encoding="utf-8")
        except OSError as error:
            print("error: generated board header missing: {}".format(error), file=sys.stderr)
            return 1
        if current != generated:
            print(
                "error: {} is stale; run {}".format(args.output, Path(__file__).name),
                file=sys.stderr,
            )
            return 1
        print("board header is up to date")
        return 0

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(generated, encoding="utf-8")
    print("generated {}".format(args.output))
    return 0


if __name__ == "__main__":
    sys.exit(main())
